services:
  mysql:
    restart: always

  migrate:
    environment:
      NODE_ENV: production

  api:
    environment:
      NODE_ENV: production
      PORT: 3000
    ports: !reset []
    restart: always

  web:
    build:
      args:
        VITE_API_URL: /api
    restart: always
